### ISSUE TITLE
CMakelists.txt looks copy-pasted from a KDE Applications repository

### ISSUE THREAD

**Issue by lbeltrame** [jimtendo/onetimepass-plasma#1]
(This issue is posted following the requests from comments in kde-devel). 

The initial part of the CMakelists.txt looks copied from the Applications repositories (in particular the "managed by release scripts" part). Ideally that part should be removed.

**Comment by jimtendo** [comment]
Thank you for your feedback here.

You are correct  - this was plucked from an application within that repository. So far as removing this is concerned, do I need to leave a comment in the CMakeLists file so that the KDE's CI scripts would know where to inject this?

**Comment by lbeltrame** [comment]
No, you may want to remove this altogether. That only works if the project is hosted on KDE infrastructure rather than GH.

**Comment by jimtendo** [comment]
Have removed this. Again, thank you for the feedback.
